# This workflow will build and run unit tests

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish Artifacts
      run: dotnet publish Shift.Left.Testing.Poc/Shift.Left.Testing.Poc.csproj -c Release -o website
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: website
        path: /home/runner/work/shift-left-testing-example/shift-left-testing-example/website/**
        if-no-files-found: error
